### ISSUE TITLE
DNS leak?

### ISSUE THREAD

**Issue by Schmashlafu** [rahmnathan/docker#2]
Hi, when I run the DNS leak test script from here: https://github.com/macvk/dnsleaktest in the deluge/airvpn container it tells me that it's using cloudflare DNS.
Shouldn't it be using airvpn DNS?
I believe this may be a DNS leak.

**Comment by rahmnathan** [comment]
Thanks for the comment @Schmashlafu. You're correct that DNS look-ups are happening outside of the vpn tunnel. This is something that I believe can be fixed quite easily, but hasn't been a priority for me as DNS exposure is not part of the threat vector I'm concerned about with this deployment.

I will try to take a look soon, but if you'd like to submit a pull request with the solution that'd be great!

**Comment by rahmnathan** [comment]
This has been resolved in the latest build: rahmnathan/airvpn:1.1.0.1
